// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";

var user = React.createContext(undefined);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = user.Provider;

function login(user) {
  return Belt_Option.map(user, (function (user) {
                return user.login;
              }));
}

export {
  user ,
  makeProps ,
  make ,
  login ,
  
}
/* user Not a pure module */
