// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Login from "./Login.bs.js";
import * as React from "react";
import * as Header from "./Header.bs.js";
import * as LinkList from "./LinkList.bs.js";
import * as CreateLink from "./CreateLink.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

((require('../styles/App.css')));

function App(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  var nowShowing;
  if (match) {
    switch (match[0]) {
      case "create" : 
          nowShowing = match[1] ? "NotFound" : React.createElement(CreateLink.make, { });
          break;
      case "login" : 
          nowShowing = match[1] ? "NotFound" : React.createElement(Login.make, { });
          break;
      default:
        nowShowing = "NotFound";
    }
  } else {
    nowShowing = React.createElement(LinkList.make, { });
  }
  return React.createElement("div", {
              className: "center w85"
            }, React.createElement(Header.make, { }), React.createElement("div", {
                  className: "ph3 pv1 background-gray"
                }, nowShowing));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
