// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Dates from "../Dates.bs.js";
import * as Token from "../Token.bs.js";
import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";

function Link(Props) {
  var link = Props.link;
  var index = Props.index;
  console.log("Upvote");
  var match = Token.isLoggedIn(/* () */0);
  return React.createElement("div", {
              className: "flex mt2 items-start"
            }, React.createElement("div", {
                  className: "flex items-center"
                }, React.createElement("span", {
                      className: "gray"
                    }, String(index + 1 | 0) + "."), match ? React.createElement("div", {
                        className: "ml1 gray f11",
                        onClick: (function (_ev) {
                            return /* () */0;
                          })
                      }, "▲") : null), React.createElement("div", {
                  className: "ml1"
                }, React.createElement("div", undefined, link[/* description */2] + (" (" + (link[/* url */3] + ") "))), React.createElement("div", {
                      className: "f6 lh-copy gray"
                    }, String(link[/* votes */4].length) + " votes | by ", Belt_Option.getWithDefault(Belt_Option.map(link[/* postedBy */5], (function (postedBy) {
                                return postedBy[/* name */1];
                              })), "Unknown "), Dates.timeDifferenceForDate(link[/* createdAt */1]))));
}

var make = Link;

export {
  make ,
  
}
/* react Not a pure module */
