// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function Link(Props) {
  var link = Props.link;
  return React.createElement("div", undefined, React.createElement("div", undefined, link.description + (" (" + (link.url + ") "))));
}

var make = Link;

export {
  make ,
  
}
/* react Not a pure module */
