// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as ReasonUrql from "reason-urql/src/ReasonUrql.bs.js";
import * as Link$ReasonHn from "./Link.bs.js";
import * as Types$ReasonHn from "../models/Types.bs.js";
import * as Queries$ReasonHn from "../graphql/Queries.bs.js";
import * as Sorting$ReasonHn from "../utils/Sorting.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

function sortLinks(links, sort) {
  if (sort) {
    return List.sort((function (a, b) {
                  return b[/* votes */4].length - a[/* votes */4].length | 0;
                }), Belt_List.fromArray(links));
  } else {
    return List.sort((function (a, b) {
                  return a[/* votes */4].length - b[/* votes */4].length | 0;
                }), Belt_List.fromArray(links));
  }
}

function TopList(Props) {
  var match = Props.path;
  if (match === undefined) {
    ReasonReactRouter.useUrl(undefined, /* () */0)[/* path */0];
  }
  var match$1 = React.useState((function () {
          return /* array */[];
        }));
  var setLinks = match$1[1];
  var request = Queries$ReasonHn.FEED_QUERY[/* make */4](10, undefined, undefined, /* () */0);
  var match$2 = Curry._4(ReasonUrql.Hooks[/* useQuery */1], request, undefined, undefined, /* () */0);
  var response = match$2[0][/* response */3];
  React.useEffect((function () {
          if (typeof response !== "number") {
            if (!response.tag) {
              var linksToRender = Types$ReasonHn.Feed[/* decodeLinks */4](response[0].feed.links);
              var linksToRender$1 = Belt_List.toArray(Sorting$ReasonHn.sortLinks(linksToRender, /* Desc */1));
              var links = Belt_Array.mapWithIndex(linksToRender$1, (function (index, link) {
                      return React.createElement(Link$ReasonHn.make, {
                                  link: link,
                                  index: index,
                                  key: link[/* id */0]
                                });
                    }));
              Curry._1(setLinks, (function (param) {
                      return links;
                    }));
            }
            
          }
          return undefined;
        }), /* array */[response]);
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, match$1[0]));
}

var make = TopList;

export {
  sortLinks ,
  make ,
  
}
/* react Not a pure module */
