// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";

function sortLinks(links, sort) {
  if (sort) {
    return List.sort((function (a, b) {
                  return b[/* votes */4].length - a[/* votes */4].length | 0;
                }), Belt_List.fromArray(links));
  } else {
    return List.sort((function (a, b) {
                  return a[/* votes */4].length - b[/* votes */4].length | 0;
                }), Belt_List.fromArray(links));
  }
}

export {
  sortLinks ,
  
}
/* No side effect */
