// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Json_decode from "@glennsl/bs-json/src/Json_decode.bs.js";
import * as Caml_chrome_debugger from "bs-platform/lib/es6/caml_chrome_debugger.js";

function decodeUser(json) {
  return /* record */Caml_chrome_debugger.record(["id"], [Json_decode.field("id", Json_decode.string, json)]);
}

function decodePostedBy(json) {
  return /* record */Caml_chrome_debugger.record([
            "id",
            "name"
          ], [
            Json_decode.field("id", Json_decode.string, json),
            Json_decode.field("name", Json_decode.string, json)
          ]);
}

function decodeVotes(json) {
  return /* record */Caml_chrome_debugger.record([
            "id",
            "user"
          ], [
            Json_decode.field("id", Json_decode.string, json),
            Json_decode.field("user", decodeUser, json)
          ]);
}

function decodeLink(json) {
  return /* record */Caml_chrome_debugger.record([
            "id",
            "createdAt",
            "description",
            "url",
            "votes",
            "postedBy"
          ], [
            Json_decode.field("id", Json_decode.string, json),
            Json_decode.field("createdAt", Json_decode.date, json),
            Json_decode.field("description", Json_decode.string, json),
            Json_decode.field("url", Json_decode.string, json),
            Json_decode.field("votes", (function (param) {
                    return Json_decode.array(decodeVotes, param);
                  }), json),
            Json_decode.optional((function (param) {
                    return Json_decode.field("postedBy", decodePostedBy, param);
                  }), json)
          ]);
}

function decodeLinks(json) {
  var json$1 = JSON.parse(Belt_Option.getExn(Caml_option.undefined_to_opt(JSON.stringify(json))));
  return Json_decode.array(decodeLink, json$1);
}

function decodeFeed(json) {
  return /* record */Caml_chrome_debugger.record([
            "links",
            "count"
          ], [
            Json_decode.field("links", (function (param) {
                    return Json_decode.array(decodeLink, param);
                  }), json),
            Json_decode.field("count", Json_decode.$$int, json)
          ]);
}

function decodeData(json) {
  return /* record */Caml_chrome_debugger.record(["feed"], [Json_decode.field("feed", decodeFeed, json)]);
}

function decode(json) {
  return decodeData(JSON.parse(Belt_Option.getExn(Caml_option.undefined_to_opt(JSON.stringify(json)))));
}

var Feed = /* module */Caml_chrome_debugger.localModule([
    "decodeUser",
    "decodePostedBy",
    "decodeVotes",
    "decodeLink",
    "decodeLinks",
    "decodeFeed",
    "decodeData",
    "decode"
  ], [
    decodeUser,
    decodePostedBy,
    decodeVotes,
    decodeLink,
    decodeLinks,
    decodeFeed,
    decodeData,
    decode
  ]);

export {
  Feed ,
  
}
/* No side effect */
