// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE


function timeDifference(current, previous) {
  var milliSecondsPerMinute = 60 * 1000;
  var milliSecondsPerHour = milliSecondsPerMinute * 60;
  var milliSecondsPerDay = milliSecondsPerHour * 24;
  var milliSecondsPerMonth = milliSecondsPerDay * 30;
  var milliSecondsPerYear = milliSecondsPerDay * 365;
  var elapsed = current - previous;
  if (elapsed < milliSecondsPerMinute / 3) {
    return "just now";
  } else if (elapsed < milliSecondsPerMinute) {
    return "less than 1 min ago";
  } else if (elapsed < milliSecondsPerHour) {
    return Math.round(elapsed / milliSecondsPerMinute).toString() + " min ago";
  } else if (elapsed < milliSecondsPerDay) {
    return Math.round(elapsed / milliSecondsPerHour).toString() + " h ago";
  } else if (elapsed < milliSecondsPerMonth) {
    return Math.round(elapsed / milliSecondsPerDay).toString() + " days ago";
  } else if (elapsed < milliSecondsPerYear) {
    return Math.round(elapsed / milliSecondsPerMonth).toString() + " mo ago";
  } else {
    return Math.round(elapsed / milliSecondsPerYear).toString() + " years ago";
  }
}

function makeDate(date) {
  return date.getTime();
}

function timeDifferenceForDate(createdAt) {
  var now = Date.now();
  var updated = createdAt.getTime();
  return timeDifference(now, updated);
}

export {
  timeDifference ,
  makeDate ,
  timeDifferenceForDate ,
  
}
/* No side effect */
