// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as App from "./components/App.bs.js";
import * as Urql from "urql";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Wonka from "wonka/src/wonka.js";
import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonUrql from "reason-urql/src/ReasonUrql.bs.js";
import * as ServiceWorker from "./serviceWorker";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";

((require('./styles/index.css')));

((require('tachyons/css/tachyons.css')));

function register_service_worker(prim) {
  ServiceWorker.register();
  return /* () */0;
}

function unregister_service_worker(prim) {
  ServiceWorker.unregister();
  return /* () */0;
}

ReasonReactRouter.push("");

function debugExchange(exchangeInput) {
  var forward = exchangeInput.forward;
  return (function (ops) {
      return Wonka.tap((function (res) {
                      console.log("[debugExchange]: Completed operation: ", res);
                      return /* () */0;
                    }))(Curry._1(forward, Wonka.tap((function (op) {
                              console.log("[debugExchange]: Incoming operation: ", op);
                              return /* () */0;
                            }))(ops)));
    });
}

var client = Curry._4(ReasonUrql.Client[/* make */3], "http://localhost:4000", undefined, /* array */[
      debugExchange,
      Urql.fetchExchange
    ], /* () */0);

ReactDOMRe.renderToElementWithId(React.createElement(Urql.Provider, {
          value: client,
          children: React.createElement(App.make, { })
        }), "root");

ServiceWorker.unregister();

export {
  register_service_worker ,
  unregister_service_worker ,
  debugExchange ,
  client ,
  
}
/*  Not a pure module */
