// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Caml_chrome_debugger from "bs-platform/lib/es6/caml_chrome_debugger.js";

function LocalStorage(K) {
  var key = K[/* key */0];
  var get = function (param) {
    return Caml_option.null_to_opt(localStorage.getItem(key));
  };
  var set = function (value) {
    localStorage.setItem(key, value);
    return /* () */0;
  };
  var remove = function (param) {
    localStorage.removeItem(key);
    return /* () */0;
  };
  return /* module */Caml_chrome_debugger.localModule([
            "key",
            "get",
            "set",
            "remove"
          ], [
            key,
            get,
            set,
            remove
          ]);
}

var key = "auth-token";

function get(param) {
  return Caml_option.null_to_opt(localStorage.getItem(key));
}

function set(value) {
  localStorage.setItem(key, value);
  return /* () */0;
}

function remove(param) {
  localStorage.removeItem(key);
  return /* () */0;
}

var Token = /* module */Caml_chrome_debugger.localModule([
    "key",
    "get",
    "set",
    "remove"
  ], [
    key,
    get,
    set,
    remove
  ]);

function getToken(param) {
  return Caml_option.null_to_opt(localStorage.getItem(key));
}

var setToken = set;

function deleteToken(param) {
  localStorage.removeItem(key);
  return /* () */0;
}

export {
  LocalStorage ,
  Token ,
  getToken ,
  setToken ,
  deleteToken ,
  
}
/* No side effect */
