// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Caml_chrome_debugger from "bs-platform/lib/es6/caml_chrome_debugger.js";

function sortTweets(tweets, sort) {
  if (sort) {
    return List.sort((function (a, b) {
                  return b[/* votes */2].length - a[/* votes */2].length | 0;
                }), Belt_List.fromArray(tweets));
  } else {
    return List.sort((function (a, b) {
                  return a[/* votes */2].length - b[/* votes */2].length | 0;
                }), Belt_List.fromArray(tweets));
  }
}

var dummyTweets = /* array */[
  /* record */Caml_chrome_debugger.record([
      "id",
      "text",
      "votes"
    ], [
      "id_1",
      "Some insightful tweet",
      [
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"])
      ]
    ]),
  /* record */Caml_chrome_debugger.record([
      "id",
      "text",
      "votes"
    ], [
      "id_2",
      "Some insightful tweet",
      [
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"])
      ]
    ]),
  /* record */Caml_chrome_debugger.record([
      "id",
      "text",
      "votes"
    ], [
      "id_3",
      "Some insightful tweet",
      [
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"])
      ]
    ]),
  /* record */Caml_chrome_debugger.record([
      "id",
      "text",
      "votes"
    ], [
      "id_4",
      "Some insightful tweet",
      [
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"])
      ]
    ]),
  /* record */Caml_chrome_debugger.record([
      "id",
      "text",
      "votes"
    ], [
      "id_5",
      "Some insightful tweet",
      [
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"])
      ]
    ]),
  /* record */Caml_chrome_debugger.record([
      "id",
      "text",
      "votes"
    ], [
      "id_6",
      "Some insightful tweet",
      [
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"])
      ]
    ]),
  /* record */Caml_chrome_debugger.record([
      "id",
      "text",
      "votes"
    ], [
      "id_7",
      "Some insightful tweet",
      [
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"])
      ]
    ]),
  /* record */Caml_chrome_debugger.record([
      "id",
      "text",
      "votes"
    ], [
      "id_8",
      "Some insightful tweet",
      [
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"])
      ]
    ]),
  /* record */Caml_chrome_debugger.record([
      "id",
      "text",
      "votes"
    ], [
      "id_9",
      "Some insightful tweet",
      [
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"])
      ]
    ]),
  /* record */Caml_chrome_debugger.record([
      "id",
      "text",
      "votes"
    ], [
      "id_10",
      "Some insightful tweet",
      [
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"]),
        /* record */Caml_chrome_debugger.record(["id"], ["ck0a0ychmjv5b0b09zlz6ps6m"])
      ]
    ])
];

function voteCount(tweet) {
  return tweet[/* votes */2].length;
}

function TweetSorting$Tweet(Props) {
  var tweet = Props.tweet;
  var index = Props.index;
  return React.createElement("div", {
              className: "flex mt2 items-start"
            }, React.createElement("div", {
                  className: "flex items-center"
                }, React.createElement("span", {
                      className: "gray"
                    }, String(index + 1 | 0) + ".")), React.createElement("div", {
                  className: "ml1"
                }, React.createElement("div", undefined, tweet[/* text */1]), React.createElement("div", {
                      className: "f6 lh-copy gray"
                    }, " votes " + String(tweet[/* votes */2].length))));
}

var Tweet = /* module */Caml_chrome_debugger.localModule(["make"], [TweetSorting$Tweet]);

function renderTweets(tweets) {
  return Belt_Array.mapWithIndex(tweets, (function (index, tweet) {
                return React.createElement(TweetSorting$Tweet, {
                            tweet: tweet,
                            index: index,
                            key: tweet[/* id */0]
                          });
              }));
}

function TweetSorting(Props) {
  var match = React.useState((function () {
          return false;
        }));
  var setToggle = match[1];
  var toggle = match[0];
  var match$1 = React.useState((function () {
          return /* Asc */0;
        }));
  var setDirection = match$1[1];
  var direction = match$1[0];
  var sorted = Belt_List.toArray(sortTweets(dummyTweets, direction));
  return React.createElement("div", undefined, React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setToggle, (function (param) {
                                    return !toggle;
                                  }));
                    })
                }, "Toggle"), toggle ? renderTweets(dummyTweets) : null, React.createElement("button", {
                  onClick: (function (param) {
                      var match = direction === /* Asc */0;
                      if (match) {
                        return Curry._1(setDirection, (function (param) {
                                      return /* Desc */1;
                                    }));
                      } else {
                        return Curry._1(setDirection, (function (param) {
                                      return /* Asc */0;
                                    }));
                      }
                    })
                }, "ToggleSorted"), renderTweets(sorted));
}

var make = TweetSorting;

export {
  sortTweets ,
  dummyTweets ,
  voteCount ,
  Tweet ,
  renderTweets ,
  make ,
  
}
/* react Not a pure module */
