// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_chrome_debugger from "bs-platform/lib/es6/caml_chrome_debugger.js";

var user = React.createContext(undefined);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = user.Provider;

function login(user) {
  return Belt_Option.map(user, (function (user) {
                return user.login;
              }));
}

var CurrentUser = /* module */Caml_chrome_debugger.localModule([
    "user",
    "makeProps",
    "make",
    "login"
  ], [
    user,
    makeProps,
    make,
    login
  ]);

export {
  CurrentUser ,
  
}
/* user Not a pure module */
